In [2]:
n=1
while(n<=20):
    if(n%2==0):
        print(n)
    n=n+1
print("thank you")

2
4
6
8
10
12
14
16
18
20
thank you


In [6]:
st=input("enter a string:")
print(st[::-1])

enter a string: piyush


hsuyip


In [12]:
strin="hello i am from jaipur"
print(strin[::2])

hloia rmjiu


In [16]:
number=int(input("enter a number:"))
fact=1
while(number>0):
           fact=fact*number2
    
           number=number-1
print(fact)


enter a number: 6


720


In [20]:
sum = 0

for num in range(1, 101):
    if num > 1:  
        flag = 0
        for i in range(2, num):
            if num % i == 0:
                flag = 1
                break
        if flag == 0:
            sum += num

print("The sum of all prime numbers between 1 and 100 is:", sum)


The sum of all prime numbers between 1 and 100 is: 1060


In [24]:
n=int(input("enter a number:"))
a=0;
b=1;
sum=0
while(n>0):
    sum=a+b;
    a=b;
    b=sum;
    n=n-1
    print(sum)

enter a number: 5


1
2
3
5
8


In [3]:
rows = int(input("Enter the number of rows: "))
for i in range(1, rows+1):
    for j in range(rows-i):
        print(" ", end="")
    for k in range(2*i-1):
        print("*", end="")
    print() 

Enter the number of rows:  5


    *
   ***
  *****
 *******
*********


# Lambda Function

A lambda function is a small anonymous function that can have any number of arguments but only one expression. It is often used for short, simple operations where defining a full function is unnecessary.

Syntax: lambda arguments: expression

Use Cases of lambda

Performing Simple Arithmetic Operations
Sorting a List of Tuples or Dictionaries
Using lambda with map(), filter(), and reduce()

In [2]:
sq=lambda x:x**2

In [4]:
sq(2)

4

In [10]:
import math

In [16]:
sq=lambda x:math.sqrt(x)

In [18]:
sq(4)

2.0

In [20]:
even_odd=lambda x:"true" if x%2==0 else "odd"

In [22]:
even_odd(5)

'odd'

In [40]:
max=lambda x,y:f"a is greater:{x}" if x>y else f"b is greater:{y}" 

In [42]:
max(4,4)

'b is greater:4'

age=lambda 

In [45]:
age=lambda a:"eligible for vote" if a>=18 else "not eligible for vote"

In [47]:
age(42)

'eligible for vote'

In [61]:
number=lambda x:"positive" if x>0 else "negative"

In [63]:
number(4)

'positive'

In [65]:
marks=lambda x:"pass" if x>=40 else "fail"

In [67]:
marks(45)

'pass'

In [69]:
year=lambda x:"leap year " if (x%4==0 & x%100!=0 & X%400==0) else "not leap year"

In [71]:
year(2025)

'not leap year'

In [91]:
words = ["Apple", "Banana", "Orange", "Grapes", "Mango"]
sorted_words = sorted(words, key=lambda x: x)
print("Sorted List:", sorted_words)


Sorted List: ['Apple', 'Banana', 'Grapes', 'Mango', 'Orange']


In [93]:
number=lambda x:"positive" if x>0 else ("negagive" if x<0 else "zero")

In [95]:
number(0)

'zero'

In [111]:
greatest=lambda x,y,z:f"x is greater{x}" if(x>y and x>z) else (f"y is greater{y}" if(y>x and y>z) else f"c is greater{z}")

In [117]:
greatest(100,400,30000)

'c is greater30000'

In [119]:
grade=lambda x:"A+" if(x>90) else ("A" if x>90 else("b" if x>75 else("c" if x>50 else "fail")))

In [121]:
grade(45)

'fail'

# Filter function

### The filter() function is used to filter elements of an iterable based on a given condition. It returns an iterator with elements that satisfy the condition.
## Syntax: filter(function, iterable)
• function: A function that returns True or False
• iterable: A sequence (list, tuple, etc.) to be filtered
Use Cases of filter()
• Filtering Even/Odd Numbers or specific data
Filtering Words in a List
• Filtering Objects Based on Attributes



In [135]:
def even(n):
    if n%2==0:
        return n


In [137]:
num=[1,2,3,4,5,6,7,8,9]

In [141]:
even=list(filter(even,num))

In [143]:
even

[2, 4, 6, 8]

In [149]:
# WAP to filter out vowels from a random strings List.  
#WAP for Filtering Even Numbers using Lambda function.  
#WAP for Filtering Words by Length ( Use Case: Extract words with more than 4 characters from  
#WAP for Filtering Students Based on Marks ( Use Case: Extract students who scored above 50 in  
def vowel(a):
    for i in range(0,len(a)):
        if(a[i]=="a" or a[i]=="e" or a[i]=="i" or  a[i]=="o" or a[i]=="u" ):
            print(a[i])

In [151]:
hell="hello how are you"

In [153]:
vo=list(filter(vowel,hell))

e
o
o
a
e
o
u


In [165]:
su=lambda x:print(x) if x%2==0 else ""

In [169]:
hello=[1,2,3,4,5,6,7,8]
e=list(filter(su,(hello)))

2
4
6
8


In [171]:
na=lambda x:print(x) if x<0 else ""

In [173]:
hello=[1,-2,-3,4,-5,6,7,8]
e=list(filter(na,(hello)))

-2
-3
-5


In [177]:
def vo(a):
    for i in range(0, len(a)):
        if a[i] == "A":
            print(a[i], end=" ")




In [181]:
heo=["Ajay","Pankaj","Ram"]
e=list(filter(vo,(heo)))

A 

In [183]:
# WAP for Filtering Students Based on Marks (📌 Use Case: Extract students who scored above 50 in an exam.)  
# Write a Python program to filter out negative numbers from a list.  
# Given a list of names, filter out names that start with the letter "A".  
# Create a program to filter out prime numbers from a given list.
sul=lambda x:print(x) if x>50 else " "

In [185]:
hello=[10,20,30,40,50,60,70,80]
e=list(filter(sul,(hello)))

60
70
80


In [187]:
names = ["Alice", "Bob", "Andrew", "Charlie", "Amanda", "David", "Alex"]

# Filtering out names that start with 'A'
filtered_names = list(filter(lambda name: not name.startswith("A"), names))

print("Original List:", names)
print("Filtered List (Without 'A' Names):", filtered_names)


Original List: ['Alice', 'Bob', 'Andrew', 'Charlie', 'Amanda', 'David', 'Alex']
Filtered List (Without 'A' Names): ['Bob', 'Charlie', 'David']


In [189]:
def to_upper(name):  
  return name.upper()  

names = ["alice", "bob", "charlie"]  
uppercase_names = list(map(to_upper, names))  


print(uppercase_names)  

['ALICE', 'BOB', 'CHARLIE']


In [197]:
list1=[1,2,3,4,5]
def square(a):
    return a**2
hi=list(map(square,list1))
print(hi)

[1, 4, 9, 16, 25]


In [202]:
list1=[1,2,3,4,5]
def double(a):
    return a*2
hi=list(map(double,list1))
print(hi)

[2, 4, 6, 8, 10]


In [206]:
# WAP for Squaring Each Element in a List  
# WAP to Calculate Final Prices with Discounts  
# Write a function that doubles each number in a List using map().  
# Use map() to convert a list of temperatures in Celsius to Fahrenheit (F = C * 9/5 + 32).  
# Given a list of words, use map() to return the length of each word.  
def temp(a):
    return a * 9/5 + 32
list1=[30,10,20,40,50]
hi=list(map(temp,list1))
print(hi)

[86.0, 50.0, 68.0, 104.0, 122.0]


# Reduce function

In [208]:
from functools import reduce

In [221]:
def max(x, y):  
    if( x > y):
        return x 
    else:
        return y

numbers = [1, 2, 3, 40, 5]  

sum_total = reduce(max, numbers)  
print(sum_total)  

40


In [235]:
def mul(x,y):  
    x=y*x;
    return x
numbers = [1, 2, 3, 40, 5]  

total = reduce(mul, numbers)  
print(total)  

1200


# numpy

In [238]:
import numpy as np


In [240]:
ar=np.array([1,2,3])

In [242]:
type(ar)

numpy.ndarray

In [246]:
ar=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [248]:
ar

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [250]:
math.random(1,6)

AttributeError: module 'math' has no attribute 'random'

In [264]:
np.random.rand([[[1,5]]])

TypeError: 'list' object cannot be interpreted as an integer

In [272]:
(np.random.rand(1,3,2))

array([[[0.3138662 , 0.61641825],
        [0.63169792, 0.32755371],
        [0.63932241, 0.50679653]]])

In [283]:
ar=np.random.randint(1, 100,(4,4))

shape of an array

In [285]:
ar.shape

(4, 4)

In [287]:
ar.size # size of an arrat

16

In [289]:
ar.ndim # dimensions of an array

2

In [291]:
len(ar) #length of an array

4

In [293]:
ar1 = np.array([[45,546,345], [234,675,43]],ndmin=16)  

In [295]:
ar1

array([[[[[[[[[[[[[[[[ 45, 546, 345],
                     [234, 675,  43]]]]]]]]]]]]]]]])

In [299]:
ar1.ndim

16

In [301]:
ar1.dtype

dtype('int32')

In [303]:
ar1.astype('float32')

array([[[[[[[[[[[[[[[[ 45., 546., 345.],
                     [234., 675.,  43.]]]]]]]]]]]]]]]], dtype=float32)

In [305]:
my_list = range(1,100)  
my_array = np.arange(1,100)  

In [307]:
import sys

In [309]:
size=sys.getsizeof(my_list[0]*len(my_list))

In [311]:
size

28

In [313]:
sizea=my_array.nbytes

In [315]:
sizea

396

In [317]:
py_list = list(range(1000))  
list_size = sys.getsizeof(py_list[0]) * len(py_list)  

# NumPy Array  
np_array = np.arange(1000)  
array_size = np_array.nbytes # Directly gives the total size  

print(f"Size of Python list: {list_size} bytes")  
print(f"Size of NumPy array: {array_size} bytes")  

Size of Python list: 28000 bytes
Size of NumPy array: 4000 bytes


In [319]:
import time  

size = 1_000_000  # 1 million elements  

# Python List  
py_list = list(range(size))  
start = time.time()  
py_list = [x * 2 for x in py_list]  # Multiply each element by 2  
end = time.time()  
print(f"Python list time: {end - start:.5f} seconds")  

# NumPy Array  
np_array = np.arange(size)  
start = time.time()  
np_array = np_array * 2  # Multiply each element by 2  
end = time.time()  
print(f"NumPy array time: {end - start:.5f} seconds")  

Python list time: 0.15489 seconds
NumPy array time: 0.00553 seconds


In [373]:
ar1 = np.array([[[1,2,3], [4,5,6],[7,8,9]]])
for i in range (0,1):
    for j in range(0,3):
        for k in range(0,3):
             ar1[i][j][k]=ar1[i][j][k]**2
print(ar1)

[[[ 1  4  9]
  [16 25 36]
  [49 64 81]]]


In [371]:
ar2 = np.array([[[1,2,3], [4,5,6],[7,8,9]]])

array([[[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]]])

In [375]:
x = [[1,2,3,4], [3,4,5,6], [6,7,8,9]]  
ar = np.array(x)  
ar  

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [6, 7, 8, 9]])

In [379]:
for i in np.nditer(ar):
    print(i)

1
2
3
4
3
4
5
6
6
7
8
9


In [381]:
ar1 = np.array([[45,546,345], [234,675,43]],ndmin=7)  

In [383]:
for i in np.nditer(ar1):
    print(i)

45
546
345
234
675
43


In [387]:
# flattern &  ravel padh le bhai

In [393]:
new_ar=ar.flatten()  

#Flatten() creates a new 1D array without modifying the original matrix.  

new_ar  

#array([1, 2, 3, 4, 5, 6, 7, 8, 9])  

ravel_ar=ar.ravel()  

# The .ravel() method returns a flattened view of the original array (if possible).  

ravel_ar  

#array([1, 2, 3, 4, 5, 6, 7, 8, 9])  

#Key Difference:  

#.ravel() does not create a new copy; it provides a view of the same data.

array([1, 2, 3, 4, 3, 4, 5, 6, 6, 7, 8, 9])

In [395]:
arr1=np.array([[1,2,3],[4,5,6]])

In [397]:
arr2=np.array([[1,2,3],[4,5,6]])

In [399]:
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [401]:
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0]])

In [403]:
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [405]:
arr1>5

array([[False, False, False],
       [False, False,  True]])

In [407]:
arr1[arr1>5]

array([6])

In [411]:
# Arange Function

In [419]:
ar=np.arange(1,100,5)#start stop step

In [421]:
ar

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [423]:
ar.size

20

In [427]:
ar.reshape(2,10)# quantity , elements

array([[ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71, 76, 81, 86, 91, 96]])

In [435]:
ar=np.arange(1,101,1)
ar.reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [431]:
ar


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
# Copy v/s View

Difference between copy and view
View can be called as a temporay. If any change made in original array will reflect on it.
Copy has its own data and can change its own data but won't reflect on the origional data

In [437]:
var=np.array([1,2,3,4,5,6,7,8,9])

In [439]:
co=var.copy()

In [441]:
co

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [443]:
vi=var.view()

In [445]:
vi

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [447]:
co[4]=45

In [449]:
var[5]=99

In [451]:
co

array([ 1,  2,  3,  4, 45,  6,  7,  8,  9])

In [453]:
var

array([ 1,  2,  3,  4,  5, 99,  7,  8,  9])

In [455]:
vi

array([ 1,  2,  3,  4,  5, 99,  7,  8,  9])

In [459]:
matrix = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13, 14, 15, 16]])
sliced = matrix[1:3, 1:4]
print(sliced)

[[ 6  7  8]
 [10 11 12]]


In [461]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [463]:
# create an array for strings and ask for its data type 

In [511]:
a=np.array(["hello ","worlld"])


In [513]:
type(a)

numpy.ndarray

In [515]:
a.dtype

dtype('<U6')

In [517]:
arr=np.array([[1,2,3],[4,5,6]],dtype="i4")

In [519]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [522]:
a=np.array([5.2,5.65])

In [524]:
a.dtype

dtype('float64')

In [530]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])

In [532]:
a3=np.concatenate((a1,a2))

In [534]:
a3

array([1, 2, 3, 4, 5, 6])

In [536]:
# stacking in nunpy 

In [538]:
#vertical stacks::::

In [540]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])

In [546]:
v=np.vstack((arr1,arr2))
print(v)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [548]:
v=np.hstack((arr1,arr2))
print(v)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [550]:
v=np.dstack((arr1,arr2))
print(v)

[[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]


In [554]:
v=np.column_stack((arr1,arr2))
print(v)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [556]:
# splitting

In [578]:
a1=np.array([1,2,3,4,5,6])

In [580]:
a2=np.array_split(a1,3)

In [582]:
a2

[array([1, 2]), array([3, 4]), array([5, 6])]

In [584]:
a2=np.array_split(a1,4)

In [586]:
a2

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [588]:
a2=np.array_split(a1,8)

In [590]:
a2

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([], dtype=int32),
 array([], dtype=int32)]

In [603]:
#a1=np.array([1,2,3,4,5,6])
#a2 = np.array_split(a1,1,axis=1)

IndexError: tuple index out of range

In [8]:
arr=np.array([1,2,3,54,6,5.5,8,45,4])


NameError: name 'np' is not defined

In [5]:
for i in range:
    if arr[i]%2==0:
        print(arr[i])

TypeError: 'type' object is not iterable

In [ ]:
a1

In [10]:
import numpy as np

# Pandas

In [13]:
import pandas as pa

In [15]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [19]:
import pandas as pd

### series in pandas

In [24]:
s=pd.Series([10,20,30,40,50])

In [26]:
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [28]:
list1=["one]","two","three"]
s=pd.Series(list1)

In [30]:
s

0     one]
1      two
2    three
dtype: object

In [32]:
s[1]

'two'

In [34]:
s=pd.Series(list1,index=["a","b","c"])

In [36]:
s

a     one]
b      two
c    three
dtype: object

In [38]:
s["b"]

'two'

In [40]:
list2=[10,20,30,40,50,60,70]

In [42]:
s=pd.Series(list2)

In [44]:
s

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [46]:
s=pd.Series(list2,index=["A","B","C","D","E","F","G"])

In [48]:
s

A    10
B    20
C    30
D    40
E    50
F    60
G    70
dtype: int64

# Series & Data Frame

In [58]:
# Creating a Vatarrame  
data = {'Name': ['Alice', 'Bob', 'Charlie','d','e','f','g','h'],  
        'Age': [25, 30, 35,40,16,48,20,12],  
        'Salary': [50000, 60000, 70000,20000,20000,1000,1100,1000],
        'DOB':[2001,2002,2003,2004,2005,2006,2007,2008],
        'COMPANY':["amazon","abc","xyz","rcat","flipcart","razorpay","phone pe","airtel"],
        'Designation':["manager","worker","seeker","worker","worker","worker","worker","worker"],}  

df = pd.DataFrame(data)  
print(df)  

      Name  Age  Salary   DOB   COMPANY Designation
0    Alice   25   50000  2001    amazon     manager
1      Bob   30   60000  2002       abc      worker
2  Charlie   35   70000  2003       xyz      seeker
3        d   40   20000  2004      rcat      worker
4        e   16   20000  2005  flipcart      worker
5        f   48    1000  2006  razorpay      worker
6        g   20    1100  2007  phone pe      worker
7        h   12    1000  2008    airtel      worker


### adding a new colomn

In [61]:
df["Gender"]=["F","M","F,","M","F,","M","F,","m"]

In [83]:
df

A   B  A+B  A**2     A**.5
0   5   8   13    25  2.236068
1   4   1    5    16  2.000000
2   5   3    8    25  2.236068
3   3   6    9     9  1.732051
4   9  65   74    81  3.000000
5  21  32   53   441  4.582576
6   8   7   15    64  2.828427

In [85]:
dic = {"A":[5,4,5,3,9,21,8],"B":[8,1,3,6,65,32,7]}

In [87]:
df=pd.DataFrame(dic)

In [69]:
df

A   B
0   5   8
1   4   1
2   5   3
3   3   6
4   9  65
5  21  32
6   8   7

In [71]:
df["A+B"]=df["A"]+df["B"]

In [73]:
df

A   B  A+B
0   5   8   13
1   4   1    5
2   5   3    8
3   3   6    9
4   9  65   74
5  21  32   53
6   8   7   15

In [75]:
df["A**2"]=df["A"]**2

In [77]:
df

A   B  A+B  A**2
0   5   8   13    25
1   4   1    5    16
2   5   3    8    25
3   3   6    9     9
4   9  65   74    81
5  21  32   53   441
6   8   7   15    64

In [79]:
df["A**.5"]=df["A"]**.5

In [81]:
df

A   B  A+B  A**2     A**.5
0   5   8   13    25  2.236068
1   4   1    5    16  2.000000
2   5   3    8    25  2.236068
3   3   6    9     9  1.732051
4   9  65   74    81  3.000000
5  21  32   53   441  4.582576
6   8   7   15    64  2.828427

In [141]:
data = {'Name': ['Alice', 'Bob', 'Charlie','d','e','f','g','h'],  
        'Age': [25, 30, 35,40,16,48,20,12],  
        'Salary': [50000, 60000, 70000,20000,20000,1000,1100,1000],
        'DOB':[2001,2002,2003,2004,2005,2006,2007,2008],
        'COMPANY':["amazon","abc","xyz","rcat","flipcart","razorpay","phone pe","airtel"],
        'Designation':["manager","worker","seeker","worker","worker","worker","worker","worker"],}  

df = pd.DataFrame(data)  
print(df)  

      Name  Age  Salary   DOB   COMPANY Designation
0    Alice   25   50000  2001    amazon     manager
1      Bob   30   60000  2002       abc      worker
2  Charlie   35   70000  2003       xyz      seeker
3        d   40   20000  2004      rcat      worker
4        e   16   20000  2005  flipcart      worker
5        f   48    1000  2006  razorpay      worker
6        g   20    1100  2007  phone pe      worker
7        h   12    1000  2008    airtel      worker


ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [95]:
a.all()

NameError: name 'a' is not defined

In [97]:
pd


<module 'pandas' from 'C:\\Users\\piyus\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py'>

In [99]:
print(pd)

<module 'pandas' from 'C:\\Users\\piyus\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py'>


In [143]:
df

Name  Age  Salary   DOB   COMPANY Designation
0    Alice   25   50000  2001    amazon     manager
1      Bob   30   60000  2002       abc      worker
2  Charlie   35   70000  2003       xyz      seeker
3        d   40   20000  2004      rcat      worker
4        e   16   20000  2005  flipcart      worker
5        f   48    1000  2006  razorpay      worker
6        g   20    1100  2007  phone pe      worker
7        h   12    1000  2008    airtel      worker

In [109]:
df["current_Age"]=2025-df["DOB"]

NameError: name 'DF' is not defined

In [135]:
df

Date  Year
0 2024-03-04  2024
1 2023-07-15  2023
2 2022-07-07  2022
3 2021-12-21  2021

In [119]:
df["age new2"]=df["DOB"].apply(lambda a:2025-a)

In [121]:
df

Name  Age  Salary   DOB   COMPANY Designation  total  current_Age  \
0    Alice   25   50000  2001    amazon     manager     24           24   
1      Bob   30   60000  2002       abc      worker     23           23   
2  Charlie   35   70000  2003       xyz      seeker     22           22   
3        d   40   20000  2004      rcat      worker     21           21   
4        e   16   20000  2005  flipcart      worker     20           20   
5        f   48    1000  2006  razorpay      worker     19           19   
6        g   20    1100  2007  phone pe      worker     18           18   
7        h   12    1000  2008    airtel      worker     17           17   

   age32  age new2  
0     24        24  
1     23        23  
2     22        22  
3     21        21  
4     20        20  
5     19        19  
6     18        18  
7     17        17

In [131]:
data = {"Date": ["2024-03-04", "2023-07-15","2022-07-07","2021-12-21"]}  
df = pd.DataFrame(data)  

# Convert 'Date' column to datetime format  
df["Date"] = pd.to_datetime(df["Date"])  

# Create a new column based on the year  
df["Year"] = df["Date"].dt.year  

In [133]:
df

Date  Year
0 2024-03-04  2024
1 2023-07-15  2023
2 2022-07-07  2022
3 2021-12-21  2021

In [145]:
df

Name  Age  Salary   DOB   COMPANY Designation
0    Alice   25   50000  2001    amazon     manager
1      Bob   30   60000  2002       abc      worker
2  Charlie   35   70000  2003       xyz      seeker
3        d   40   20000  2004      rcat      worker
4        e   16   20000  2005  flipcart      worker
5        f   48    1000  2006  razorpay      worker
6        g   20    1100  2007  phone pe      worker
7        h   12    1000  2008    airtel      worker

In [147]:
df["COMPANY"]

0      amazon
1         abc
2         xyz
3        rcat
4    flipcart
5    razorpay
6    phone pe
7      airtel
Name: COMPANY, dtype: object

In [151]:
df[["COMPANY","Salary"]]

COMPANY  Salary
0    amazon   50000
1       abc   60000
2       xyz   70000
3      rcat   20000
4  flipcart   20000
5  razorpay    1000
6  phone pe    1100
7    airtel    1000

In [153]:
df["voter"]=df["Age"]>18

In [155]:
df

Name  Age  Salary   DOB   COMPANY Designation  voter
0    Alice   25   50000  2001    amazon     manager   True
1      Bob   30   60000  2002       abc      worker   True
2  Charlie   35   70000  2003       xyz      seeker   True
3        d   40   20000  2004      rcat      worker   True
4        e   16   20000  2005  flipcart      worker  False
5        f   48    1000  2006  razorpay      worker   True
6        g   20    1100  2007  phone pe      worker   True
7        h   12    1000  2008    airtel      worker  False

In [157]:
df

Name  Age  Salary   DOB   COMPANY Designation  voter
0    Alice   25   50000  2001    amazon     manager   True
1      Bob   30   60000  2002       abc      worker   True
2  Charlie   35   70000  2003       xyz      seeker   True
3        d   40   20000  2004      rcat      worker   True
4        e   16   20000  2005  flipcart      worker  False
5        f   48    1000  2006  razorpay      worker   True
6        g   20    1100  2007  phone pe      worker   True
7        h   12    1000  2008    airtel      worker  False

In [159]:
data = {'Name': ['Alice', 'Bob', np.nan],
        'Age': [25, np.nan, 35],
        'Salary': [50000, 60000, np.nan]}

In [161]:
df=pd.DataFrame(data)

In [163]:
df

Name   Age   Salary
0  Alice  25.0  50000.0
1    Bob   NaN  60000.0
2    NaN  35.0      NaN

In [165]:
df.fillna(0,inplace=True)

In [167]:
df

Name   Age   Salary
0  Alice  25.0  50000.0
1    Bob   0.0  60000.0
2      0  35.0      0.0

# data cleaning and transformation

In [174]:
df.head(2) #by default it give five value from start point

Name   Age   Salary
0  Alice  25.0  50000.0
1    Bob   0.0  60000.0

In [176]:
df.tail() #by default take 5 value from last 

Name   Age   Salary
0  Alice  25.0  50000.0
1    Bob   0.0  60000.0
2      0  35.0      0.0

In [178]:
df.drop_duplicates(inplace=True)

In [180]:
df

Name   Age   Salary
0  Alice  25.0  50000.0
1    Bob   0.0  60000.0
2      0  35.0      0.0

In [184]:
df.rename(columns={'name':'Employee_Name'},inplace=True)

In [188]:
data = {'Department': ['HR', 'IT', 'HR', 'IT'],
        'Salary': [50000, 70000, 60000, 80000]}

In [190]:
df=pd.DataFrame(data)
print(df.groupby('Department').mean())

             Salary
Department         
HR          55000.0
IT          75000.0


In [198]:
df1 = pd.DataFrame({'ID': [1, 2], 'Name': ['Alice', 'Bob']})
df2 = pd.DataFrame({'ID': [1, 3], 'Salary': [50000, 60000]})

merged_df = pd.merge(df1, df2, on='ID')
print(merged_df)

   ID   Name  Salary
0   1  Alice   50000


In [282]:
df=pd.read_csv(r"C:\Users\piyus\Downloads\countriesoftheworld\countries of the world.csv")

In [284]:
df

Country                               Region  Population  \
0       Afghanistan         ASIA (EX. NEAR EAST)             31056997   
1           Albania   EASTERN EUROPE                          3581655   
2           Algeria   NORTHERN AFRICA                        32930091   
3    American Samoa   OCEANIA                                   57794   
4           Andorra   WESTERN EUROPE                            71201   
..               ...                                  ...         ...   
222       West Bank   NEAR EAST                               2460492   
223  Western Sahara   NORTHERN AFRICA                          273008   
224           Yemen   NEAR EAST                              21456188   
225          Zambia   SUB-SAHARAN AFRICA                     11502010   
226        Zimbabwe   SUB-SAHARAN AFRICA                     12236805   

     Area (sq. mi.) Pop. Density (per sq. mi.) Coastline (coast/area ratio)  \
0            647500                       48,0                         0,00   
1             28748                      124,6                         1,26   
2           2381740                       13,8                         0,04   
3               199                      290,4                        58,29   
4               468                      152,1                         0,00   
..              ...                        ...                          ...   
222            5860                      419,9                         0,00   
223          266000                        1,0                         0,42   
224          527970                       40,6                         0,36   
225          752614                       15,3                         0,00   
226          390580                       31,3                         0,00   

    Net migration Infant mortality (per 1000 births)  GDP ($ per capita)  \
0           23,06                             163,07               700.0   
1           -4,93                              21,52              4500.0   
2           -0,39                                 31              6000.0   
3          -20,71                               9,27              8000.0   
4             6,6                               4,05             19000.0   
..            ...                                ...                 ...   
222          2,98                              19,62               800.0   
223           NaN                                NaN                 NaN   
224             0                               61,5               800.0   
225             0                              88,29               800.0   
226             0                              67,69              1900.0   

    Literacy (%) Phones (per 1000) Arable (%) Crops (%) Other (%) Climate  \
0           36,0               3,2      12,13      0,22     87,65       1   
1           86,5              71,2      21,09      4,42     74,49       3   
2           70,0              78,1       3,22      0,25     96,53       1   
3           97,0             259,5         10        15        75       2   
4          100,0             497,2       2,22         0     97,78       3   
..           ...               ...        ...       ...       ...     ...   
222          NaN             145,2       16,9     18,97     64,13       3   
223          NaN               NaN       0,02         0     99,98       1   
224         50,2              37,2       2,78      0,24     96,98       1   
225         80,6               8,2       7,08      0,03      92,9       2   
226         90,7              26,8       8,32      0,34     91,34       2   

    Birthrate Deathrate Agriculture Industry Service  
0        46,6     20,34        0,38     0,24    0,38  
1       15,11      5,22       0,232    0,188   0,579  
2       17,14      4,61       0,101      0,6   0,298  
3       22,46      3,27         NaN      NaN     NaN  
4        8,71      6,25         NaN      NaN     NaN  
..        ...      

In [286]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 20 columns):
 #   Column                              Non-Null Count  Dtype  
---  ------                              --------------  -----  
 0   Country                             227 non-null    object 
 1   Region                              227 non-null    object 
 2   Population                          227 non-null    int64  
 3   Area (sq. mi.)                      227 non-null    int64  
 4   Pop. Density (per sq. mi.)          227 non-null    object 
 5   Coastline (coast/area ratio)        227 non-null    object 
 6   Net migration                       224 non-null    object 
 7   Infant mortality (per 1000 births)  224 non-null    object 
 8   GDP ($ per capita)                  226 non-null    float64
 9   Literacy (%)                        209 non-null    object 
 10  Phones (per 1000)                   223 non-null    object 
 11  Arable (%)                          225 non-n

In [288]:
df.size

4540

In [290]:
df.head(7)

Country                               Region  Population  \
0     Afghanistan         ASIA (EX. NEAR EAST)             31056997   
1         Albania   EASTERN EUROPE                          3581655   
2         Algeria   NORTHERN AFRICA                        32930091   
3  American Samoa   OCEANIA                                   57794   
4         Andorra   WESTERN EUROPE                            71201   
5          Angola   SUB-SAHARAN AFRICA                     12127071   
6        Anguilla               LATIN AMER. & CARIB           13477   

   Area (sq. mi.) Pop. Density (per sq. mi.) Coastline (coast/area ratio)  \
0          647500                       48,0                         0,00   
1           28748                      124,6                         1,26   
2         2381740                       13,8                         0,04   
3             199                      290,4                        58,29   
4             468                      152,1                         0,00   
5         1246700                        9,7                         0,13   
6             102                      132,1                        59,80   

  Net migration Infant mortality (per 1000 births)  GDP ($ per capita)  \
0         23,06                             163,07               700.0   
1         -4,93                              21,52              4500.0   
2         -0,39                                 31              6000.0   
3        -20,71                               9,27              8000.0   
4           6,6                               4,05             19000.0   
5             0                             191,19              1900.0   
6         10,76                              21,03              8600.0   

  Literacy (%) Phones (per 1000) Arable (%) Crops (%) Other (%) Climate  \
0         36,0               3,2      12,13      0,22     87,65       1   
1         86,5              71,2      21,09      4,42     74,49       3   
2         70,0              78,1       3,22      0,25     96,53       1   
3         97,0             259,5         10        15        75       2   
4        100,0             497,2       2,22         0     97,78       3   
5         42,0               7,8       2,41      0,24     97,35     NaN   
6         95,0             460,0          0         0       100       2   

  Birthrate Deathrate Agriculture Industry Service  
0      46,6     20,34        0,38     0,24    0,38  
1     15,11      5,22       0,232    0,188   0,579  
2     17,14      4,61       0,101      0,6   0,298  
3     22,46      3,27         NaN      NaN     NaN  
4      8,71      6,25         NaN      NaN     NaN  
5     45,11      24,2       0,096    0,658   0,246  
6     14,17      5,34        0,04     0,18    0,78

In [292]:
df.tail(12)

Country                               Region  Population  \
215            Uruguay               LATIN AMER. & CARIB         3431932   
216         Uzbekistan                  C.W. OF IND. STATES     27307134   
217            Vanuatu   OCEANIA                                  208869   
218          Venezuela               LATIN AMER. & CARIB        25730435   
219            Vietnam         ASIA (EX. NEAR EAST)             84402966   
220     Virgin Islands               LATIN AMER. & CARIB          108605   
221  Wallis and Futuna   OCEANIA                                   16025   
222          West Bank   NEAR EAST                               2460492   
223     Western Sahara   NORTHERN AFRICA                          273008   
224              Yemen   NEAR EAST                              21456188   
225             Zambia   SUB-SAHARAN AFRICA                     11502010   
226           Zimbabwe   SUB-SAHARAN AFRICA                     12236805   

     Area (sq. mi.) Pop. Density (per sq. mi.) Coastline (coast/area ratio)  \
215          176220                       19,5                         0,37   
216          447400                       61,0                         0,00   
217           12200                       17,1                        20,72   
218          912050                       28,2                         0,31   
219          329560                      256,1                         1,05   
220            1910                       56,9                         9,84   
221             274                       58,5                        47,08   
222            5860                      419,9                         0,00   
223          266000                        1,0                         0,42   
224          527970                       40,6                         0,36   
225          752614                       15,3                         0,00   
226          390580                       31,3                         0,00   

    Net migration Infant mortality (per 1000 births)  GDP ($ per capita)  \
215         -0,32                              11,95             12800.0   
216         -1,72                               71,1              1700.0   
217             0                              55,16              2900.0   
218         -0,04                               22,2              4800.0   
219         -0,45                              25,95              2500.0   
220         -8,94                               8,03             17200.0   
221           NaN                                NaN              3700.0   
222          2,98                              19,62               800.0   
223           NaN                                NaN                 NaN   
224             0                               61,5               800.0   
225             0                              88,29               800.0   
226             0                              67,69              1900.0   

    Literacy (%) Phones (per 1000) Arable (%) Crops (%) Other (%) Climate  \
215         98,0             291,4       7,43      0,23     92,34       3   
216         99,3              62,9      10,83      0,83     88,34       1   
217         53,0              32,6       2,46      7,38     90,16       2   
218         93,4             140,1       2,95      0,92     96,13       2   
219         90,3             187,7      19,97      5,95     74,08       2   
220          NaN             652,8      11,76      2,94      85,3       2   
221         50,0             118,6          5        25        70       2   
222          NaN             145,2       16,9     18,97     64,13       3   
223          NaN               NaN       0,02         0     99,98       1   
224         50,2              37,2       2,78      0,24     96,98       1   
225         80,6               8,2       7,08      0,03      92,9       2   
226         90,7              26,8       8,32      0,34     91,34       2   

    Birt

In [294]:
df["Region"]

0            ASIA (EX. NEAR EAST)         
1      EASTERN EUROPE                     
2      NORTHERN AFRICA                    
3      OCEANIA                            
4      WESTERN EUROPE                     
                      ...                 
222    NEAR EAST                          
223    NORTHERN AFRICA                    
224    NEAR EAST                          
225    SUB-SAHARAN AFRICA                 
226    SUB-SAHARAN AFRICA                 
Name: Region, Length: 227, dtype: object

In [296]:
df.loc[2]

Country                                                          Algeria 
Region                                NORTHERN AFRICA                    
Population                                                       32930091
Area (sq. mi.)                                                    2381740
Pop. Density (per sq. mi.)                                           13,8
Coastline (coast/area ratio)                                         0,04
Net migration                                                       -0,39
Infant mortality (per 1000 births)                                     31
GDP ($ per capita)                                                 6000.0
Literacy (%)                                                         70,0
Phones (per 1000)                                                    78,1
Arable (%)                                                           3,22
Crops (%)                                                            0,25
Other (%)                             

In [298]:
df=df.set_index["Country"]

TypeError: 'method' object is not subscriptable

In [300]:
df = df.set_index("Country")


In [302]:
df

Region  Population  \
Country                                                            
Afghanistan            ASIA (EX. NEAR EAST)             31056997   
Albania          EASTERN EUROPE                          3581655   
Algeria          NORTHERN AFRICA                        32930091   
American Samoa   OCEANIA                                   57794   
Andorra          WESTERN EUROPE                            71201   
...                                              ...         ...   
West Bank        NEAR EAST                               2460492   
Western Sahara   NORTHERN AFRICA                          273008   
Yemen            NEAR EAST                              21456188   
Zambia           SUB-SAHARAN AFRICA                     11502010   
Zimbabwe         SUB-SAHARAN AFRICA                     12236805   

                 Area (sq. mi.) Pop. Density (per sq. mi.)  \
Country                                                      
Afghanistan              647500                       48,0   
Albania                   28748                      124,6   
Algeria                 2381740                       13,8   
American Samoa              199                      290,4   
Andorra                     468                      152,1   
...                         ...                        ...   
West Bank                  5860                      419,9   
Western Sahara           266000                        1,0   
Yemen                    527970                       40,6   
Zambia                   752614                       15,3   
Zimbabwe                 390580                       31,3   

                Coastline (coast/area ratio) Net migration  \
Country                                                      
Afghanistan                             0,00         23,06   
Albania                                 1,26         -4,93   
Algeria                                 0,04         -0,39   
American Samoa                         58,29        -20,71   
Andorra                                 0,00           6,6   
...                                      ...           ...   
West Bank                               0,00          2,98   
Western Sahara                          0,42           NaN   
Yemen                                   0,36             0   
Zambia                                  0,00             0   
Zimbabwe                                0,00             0   

                Infant mortality (per 1000 births)  GDP ($ per capita)  \
Country                                                                  
Afghanistan                                 163,07               700.0   
Albania                                      21,52              4500.0   
Algeria                                         31              6000.0   
American Samoa                                9,27              8000.0   
Andorra                                       4,05             19000.0   
...                                            ...                 ...   
West Bank                                    19,62               800.0   
Western Sahara                                 NaN                 NaN   
Yemen                                         61,5               800.0   
Zambia                                       88,29               800.0   
Zimbabwe                                     67,69              1900.0   

                Literacy (%) Phones (per 1000) Arable (%) Crops (%) Other (%)  \
Country                                                                         
Afghanistan             36,0               3,2      12,13      0,22     87,65   
Albania                 86,5              71,2      21,09      4,42     74,49   
Algeria                 70,0              78,1       3,22      0,25     96,53   
American Samoa          97,0             259,5         10        15        75   
Andorra                100,0             497,2       2,22         0     97,78   
...              

In [304]:
df.loc["Albania"]


KeyError: 'Albania'

In [ ]:
print(df.index)

In [307]:
df.loc("Albania")


ValueError: No axis named Albania for object type DataFrame

In [309]:
df.index = df.index.str.strip()


In [314]:
df 

Region  Population  \
Country                                                           
Afghanistan           ASIA (EX. NEAR EAST)             31056997   
Albania         EASTERN EUROPE                          3581655   
Algeria         NORTHERN AFRICA                        32930091   
American Samoa  OCEANIA                                   57794   
Andorra         WESTERN EUROPE                            71201   
...                                             ...         ...   
West Bank       NEAR EAST                               2460492   
Western Sahara  NORTHERN AFRICA                          273008   
Yemen           NEAR EAST                              21456188   
Zambia          SUB-SAHARAN AFRICA                     11502010   
Zimbabwe        SUB-SAHARAN AFRICA                     12236805   

                Area (sq. mi.) Pop. Density (per sq. mi.)  \
Country                                                     
Afghanistan             647500                       48,0   
Albania                  28748                      124,6   
Algeria                2381740                       13,8   
American Samoa             199                      290,4   
Andorra                    468                      152,1   
...                        ...                        ...   
West Bank                 5860                      419,9   
Western Sahara          266000                        1,0   
Yemen                   527970                       40,6   
Zambia                  752614                       15,3   
Zimbabwe                390580                       31,3   

               Coastline (coast/area ratio) Net migration  \
Country                                                     
Afghanistan                            0,00         23,06   
Albania                                1,26         -4,93   
Algeria                                0,04         -0,39   
American Samoa                        58,29        -20,71   
Andorra                                0,00           6,6   
...                                     ...           ...   
West Bank                              0,00          2,98   
Western Sahara                         0,42           NaN   
Yemen                                  0,36             0   
Zambia                                 0,00             0   
Zimbabwe                               0,00             0   

               Infant mortality (per 1000 births)  GDP ($ per capita)  \
Country                                                                 
Afghanistan                                163,07               700.0   
Albania                                     21,52              4500.0   
Algeria                                        31              6000.0   
American Samoa                               9,27              8000.0   
Andorra                                      4,05             19000.0   
...                                           ...                 ...   
West Bank                                   19,62               800.0   
Western Sahara                                NaN                 NaN   
Yemen                                        61,5               800.0   
Zambia                                      88,29               800.0   
Zimbabwe                                    67,69              1900.0   

               Literacy (%) Phones (per 1000) Arable (%) Crops (%) Other (%)  \
Country                                                                        
Afghanistan            36,0               3,2      12,13      0,22     87,65   
Albania                86,5              71,2      21,09      4,42     74,49   
Algeria                70,0              78,1       3,22      0,25     96,53   
American Samoa         97,0             259,5         10        15        75   
Andorra               100,0             497,2       2,22         0     97,78   
...                     ...               ...        ...       ...       ..

In [318]:
#import matplotlib.pyplot as plt

#df['Salary'].plot(kind='bar')
#plt.show()
df.loc["Albania"]


Region                                EASTERN EUROPE                     
Population                                                        3581655
Area (sq. mi.)                                                      28748
Pop. Density (per sq. mi.)                                          124,6
Coastline (coast/area ratio)                                         1,26
Net migration                                                       -4,93
Infant mortality (per 1000 births)                                  21,52
GDP ($ per capita)                                                 4500.0
Literacy (%)                                                         86,5
Phones (per 1000)                                                    71,2
Arable (%)                                                          21,09
Crops (%)                                                            4,42
Other (%)                                                           74,49
Climate                               

In [1]:
#Below 18.5 → "Underweight"
#18.5 - 24.9 → "Normal weight"
#25 - 29.9 → "Overweight"
#30 and above → "Obese"
BMI=lambda x:"underweight" if (x<18.5) else ("normal weight" if (x>18.5 and x<24.9) else ("overweight" if (x>25 and x<29.9) else "obese"))

In [3]:
BMI(60)

'obese'

In [9]:
is_prime = lambda n: "prime" if n > 1 and all(n % i != 0 for i in range(2, int(n**0.5) + 1)) else "composite" if n > 1 else "zero"

# Example usage:
number = 17
print(is_prime(number))  # Output: prime
   
    

prime
